name: need changeset

on:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/changeset.yaml"

jobs:
  test-lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install
        run: make -f ci.mk install
      - name: check changesets
        run: make -f ci.mk check_changesets
        if: github.actor != 'dependabot[bot]' && github.actor != 'FluctMember'
