name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.ref }}
          token: ${{ secrets.FLUCT_MEMBER_GITHUB_TOKEN }}
      - name: Unshallow
        run: git fetch --prune --unshallow --tags
      - name: Use Node.js 18.x
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 18.x
      - name: install
        run: make -f ci.mk install
      - name: lint
        run: make -f ci.mk lint
      - name: test
        run: make -f ci.mk test
      - name: build
        run: make -f ci.mk build
      - name: Create Release Pull Request or Publish to npm
        id: check_changesets
        uses: changesets/action@e0538e686673de0265c8a3e2904b8c76beaa43fd # v1.5.2
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.FLUCT_MEMBER_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.FLUCT_NPM_TOKEN }}
