name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}
          token: ${{ secrets.FLUCT_MEMBER_GITHUB_TOKEN }}
      - name: Unshallow
        run: git fetch --prune --unshallow --tags
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install
        run: make -f ci.mk install
      - name: lint
        run: make -f ci.mk lint
      - name: test
        run: make -f ci.mk test
      - name: build
        run: make -f ci.mk build
      - name: Create Release Pull Request or Publish to npm
        id: check_changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.FLUCT_MEMBER_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.FLUCT_NPM_TOKEN }}
