name: release

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        description: release version

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      - name: Unshallow
        run: git fetch --prune --unshallow --tags
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install
        run: make -f ci.mk install
      - name: lint
        run: make -f ci.mk lint
      - name: test
        run: make -f ci.mk test
      - name: Use Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: install github_changelog_generate
        run: gem install -N github_changelog_generator
      - name: create CHANGELOG
        run: make -f ci.mk changelog
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          GITHUB_TOKEN: ${{ secrets.FLUCT_MEMBER_GITHUB_TOKEN }}
      - name: npm version
        run: make -f ci.mk release_version
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      - name: git config
        run: |
          git config --local user.name ${{ secrets.FLUCT_MEMBER_GITHUB_USER_NAME }}
          git config --local user.email ${{ secrets.FLUCT_MEMBER_GITHUB_USER_EMAIL }}
      - name: git add & commit & push
        run: |
          git add CHANGELOG.md package.json
          git commit -m "[ci skip] release v${{ env.RELEASE_VERSION }}"
          git push
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      - name: npm publish
        run: make -f ci.mk publish
        env:
          NPM_TOKEN: ${{ secrets.FLUCT_NPM_TOKEN }}
      - name: Create Release Note
        run: make -f ci.mk release_note
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          OUTPUT_FILE: release_note.md
          GITHUB_TOKEN: ${{ secrets.FLUCT_MEMBER_GITHUB_TOKEN }}
      - name: Create Tag & Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ env.RELEASE_TAG_NAME }}
          tag: ${{ env.RELEASE_TAG_NAME }}
          token: ${{ secrets.FLUCT_MEMBER_GITHUB_TOKEN }}
          bodyFile: release_note.md
        env:
          RELEASE_TAG_NAME: v${{ github.event.inputs.release_version }}
